sudo: required
dist: trusty
language: php
php:
  - '7.1'

install:
  - ./build/install_dependencies_ubuntu14.sh
  - dotnet restore ./Peachpie.sln /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Runtime/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Library/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Library.Graphics/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Library.Network/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Library.XmlDom/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Library.Scripting/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Library.MsSql/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Library.MySql/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/PDO/Peachpie.Library.PDO/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/PDO/Peachpie.Library.PDO.MySQL/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/PDO/Peachpie.Library.PDO.SqlSrv/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.App/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.CodeAnalysis/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet restore ./src/Peachpie.Compiler.Tools/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.Compiler.Tools/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.AspNetCore.Web/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.AspNetCore.Mvc/ /p:TargetFrameworks=netcoreapp2.0
  - dotnet build ./src/Peachpie.NET.Sdk/ /p:TargetFrameworks=netcoreapp2.0
  - powershell -File ./build/update-cache.ps1 0.9.9
  - dotnet restore ./src/Tests/Peachpie.DiagnosticTests/

script:
  - dotnet test ./src/Tests/Peachpie.DiagnosticTests/Peachpie.DiagnosticTests.csproj
  - ./src/Tools/runtests_shell/runtests.sh
